runtime: java11
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min-instances: 4
  max-concurrent-requests: 80
  min-pending-latency: 6s
  max-pending-latency: 10s
network: {}